### ISSUE TITLE
This list is not being updated automatically.

### ISSUE THREAD

**Issue by gurumukhi** [MozillaIndia/devs#4]
Though I didn't get into the code, it seems that this list is not being updated directly from BMO. How can we do that ?

**Comment by InderdeepBajwa** [comment]
I'm sorry I couldn't find any link to the post. May I know which list you're referring to?

**Comment by asdofindia** [comment]
This issue is probably about the [developer leaderboard](http://dev.mozillaindia.org/leaderboard/) the code for which resides at [github.com/MozillaIndia/leaderboard](https://github.com/MozillaIndia/leaderboard).
