### ISSUE TITLE
No form link present on http://devs.mozillaindia.org/start/

### ISSUE THREAD

**Issue by tsl143** [MozillaIndia/devs#6]
![screenshot from 2016-07-30 14 23 54](https://cloud.githubusercontent.com/assets/5318732/17269257/5cf424c2-5661-11e6-9107-f3b65625b4a5.png)

**Comment by asdofindia** [comment]
Already known in #5. How should we go about this?

I've been thinking about linking to a github new issue with some query variables that includes a template for example, like [this](https://github.com/MozillaIndia/mozillaindia.github.io/issues/new?title=%5Bjoin%5D+My+Name&body=%23%23+Why+do+I+want+to+become+a+MahaDev+%23%23%0D%0A%0D%0ABecause...%0D%0A%0D%0A%23%23+My+Mozillians+profile+%23%23%0D%0A%0D%0Ahttps%3A%2F%2Fmozillians.org%2Fu%2F...%0D%0A%0D%0A%23%23+My+tech+interests+%23%23%0D%0A%0D%0AI+like+to+....).

We can then use the info in the issue to onboard the person.

**Comment by RCMainak** [comment]
The issue option is a good one. That being said I am not sure if ~~everybody~~ all the new comers have an github account & have knowledge to fill out the issue properly. All though we can ask to provide correct info from the applicant on that issue.

What's wrong with google forms? Maintainability??

**Comment by asdofindia** [comment]
Nothing wrong in Google forms. Except it is kind of a mystery who signed up, what will happen after sign up, etc.
Not necessarily true though. The Google form spreadsheet can be made public.

**Comment by RCMainak** [comment]
yeah, me too feels like GitHub is more open from that point. Anyway what will happen after people signs up?

I think automating stuff will be easier using google spreadsheets & forms. If we're going for a long run then it's a thing we should keep in mind as well.

**Comment by asdofindia** [comment]
That's the real question. Who will take care of on-boarding.

Also, now that there's been a restructure of mozilla india, where does it put us?

**Comment by RCMainak** [comment]
I'm a bit confused as what purpose will this list serve. Please clarify that as well. Is it only for the vouched Mozillians in India or for anyone who wants to join. Are we going to track if the people in the lists is active or not? What are the possible way to track such thing if we're interested in keep the list clean. In simple words asking for the criteria to get on that list if there is any.

**Comment by asdofindia** [comment]
The way I envisioned it I was thinking of a hacker community inside mozilla india in which anyone could join - to share their knowledge, learn from others, etc - and helps to instill the hacker culture in the community.

**Comment by InderdeepBajwa** [comment]
Okay, so here I am.
I can integrate Google forms, hide them using HTML and give a hint on the page that it is hidden. It will be only hidden using simple HTML including a hint using HTML comment. This will allow only serious contributors who have experience to submit the form; hence, keeping others away.
And I am interested in filtering out participants I will find interesting by looking at the profile provided by them in the form.
Is this a good idea?

**Comment by asdofindia** [comment]
We've to think of what the purpose of the form is, before figuring out how to deploy it.

**Comment by InderdeepBajwa** [comment]
The idea MahaDevs will make people contribute to Mozilla thinking it's different from actual boring Mozilla contribution (as they think).
I'll setup a survey from Mozilla to know if they want something rewarding instead of normal Mozilla contribution.  Can we talk on telegram?

**Comment by RCMainak** [comment]
I don't understand what is the purpose of the form hidden. I'm also confused about the term "boring Mozilla contribution". There are many projects available out there which requires serious contributors. If someone wants to contribute they'll be overwhelmed by the amount of projects going on. I'm not a big fan of close stuff, all though I can appreciate the idea of solving puzzle & stuff.

@asdofindia when are we planning to make the Mahadev thing live?

**Comment by InderdeepBajwa** [comment]
Yes definitely @RCMainak. Mozilla is interesting, but a normal person can not find direct links to something he wants to contribute. With MahaDev, we can provide users with direct links so as to get better participation.
Mozilla Punjab community collapsed just because of this reason. There's no opportunity they said; as people informed me. I'm new to it no doubt. But it doesn't feels great when Mozilla website has lot of Wiki stuff but no direct links. General public is just open to AoA, writing articles on their 'own' blogs and looking for nearby meetups.
We could make something simpler.
Does Mozilla has marketing branch? Does it has promotion branch?

**Comment by NidhxGupta** [comment]
Hi @asdofindia ! 
Do u have a form link ready? Or will we have to create one?

**Comment by asdofindia** [comment]
We don't have any form. I think it maybe a good idea to directly link to a telegram group where friendly humans can interact rather than making people fill up a form. 

I have requested @debloper to create a URL for a telegram group we are already talking in.

**Comment by NidhxGupta** [comment]
Okay that sounds great! I have updated the same in #10 
![Screenshot 2019-10-31 at 8 57 05 AM](https://user-images.githubusercontent.com/56179878/67916721-9d1f2c00-fbbc-11e9-9705-f9c119b855ce.png)
Here is what the page would look like after making the changes. We will only have to update the Telegram Group Link.

**Comment by asdofindia** [comment]
Here is [the link](https://t.me/joinchat/AFfAPBY1C4c4lGdAy9bdMw)

**Comment by NidhxGupta** [comment]
Added the link in #10

**Comment by asdofindia** [comment]
Fixed by #10
