### ISSUE TITLE
Link mentioned on README.md file isn't working.

### ISSUE THREAD

**Issue by NidhxGupta** [MozillaIndia/devs#9]
I'm not able to access "http://devs.mozillaindia.org" link mentioned in this file. I think it needs to be updated.
![Screenshot 2019-10-29 at 2 59 12 PM](https://user-images.githubusercontent.com/56179878/67754801-11db5480-fa5d-11e9-9f76-77d68b5f7371.png)
Here is what I get when I try visiting the link:
![Screenshot 2019-10-29 at 3 00 02 PM](https://user-images.githubusercontent.com/56179878/67754853-24558e00-fa5d-11e9-926d-2d9a3a58fc60.png)

**Comment by asdofindia** [comment]
Yes. The link needs to be mozillaindia.org/devs/

Do you want to fix it?

**Comment by NidhxGupta** [comment]
I've added the correct link. #10

**Comment by NidhxGupta** [comment]
I think the main github page for @MozillaIndia should be updated as well. The link should be mozillaindia.org/devs/ as you mentioned above.
![Link Correction](https://user-images.githubusercontent.com/56179878/67912269-6ee71f80-fbaf-11e9-8b2b-05df5cf885b4.png)

**Comment by asdofindia** [comment]
Fixed by #10
